project_name: cloudsword
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - darwin
      - windows
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    ldflags:
      - -s -w
      - -X github.com/wgpsec/cloudsword/utils/global.Version={{.Version}}
      - -X github.com/wgpsec/cloudsword/utils/global.UpdateDate={{.Date}}
archives:
  - name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    id: homebrew
    format: zip
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE
      - static/*
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^doc:"
      - "^ci:"
      - "^Merge pull request"
brews:
  - ids:
      - homebrew
    name: cloudsword
    tap:
      owner: wgpsec
      name: homebrew-tap
      branch: master
    folder: Formula
    url_template: "https://github.com/wgpsec/cloudsword/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://wiki.teamssix.com/cloudsword"
    description: "CloudSword is a public cloud security exploitation tool."
    skip_upload: auto
    install: |-
      bin.install "cloudsword"